version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: qc_postgres_new
    environment:
      POSTGRES_USER: quantum_user
      POSTGRES_PASSWORD: quantum_secure_pass_123
      POSTGRES_DB: quantum_commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: qc_redis_new
    command: redis-server --requirepass redis_secure_pass_456
    ports:
      - "6379:6379"
    volumes:
      - redis_data_new:/data

  vault:
    image: hashicorp/vault:1.15
    container_name: qc_vault_new
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev_vault_token_789
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: vault server -dev

volumes:
  postgres_data_new:
  redis_data_new:
