version: '3.8'

services:
  # PostgreSQL Database only
  postgres:
    image: postgres:15-alpine
    container_name: qsc_postgres
    environment:
      POSTGRES_DB: quantum_commerce
      POSTGRES_USER: qsc_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache only
  redis:
    image: redis:7-alpine
    container_name: qsc_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

volumes:
  postgres_data: