services:
  - type: web
    name: quantum-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quantum-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: quantum-db
    plan: free
    databaseName: quantum_commerce
    user: qsc_user
