global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quantum-commerce-api'
    static_configs:
      - targets: ['qc_api:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_timeout: 10s
