groups:
  - name: quantum_commerce_alerts
    rules:
      # API availability
      - alert: QuantumAPIDown
        expr: up{job="quantum-commerce-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Quantum Commerce API is down"
          description: "The quantum-secure API has been down for more than 1 minute"
      
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"
